language: r
pandoc_version: 1.19.2.1
before_script:
- chmod +x ./website/_build.sh
- chmod +x ./website/_deploy.sh
script:
- "./website/_build.sh"
- "./website/_deploy.sh"
env:
  global:
    secure: 2Pl8rjgD4p1whBbx6BcSQ9jivx5ee3q3roP4NLgMsNYR/g5rv0RtTAjRLqdhtMKi4z+KBQQwI+xQGTURVCUF1SiNxseq/5tnEDu3IwDwlvkzm/oIMoeabdHCin2NYPt6tcebQLUvdAa+E/e2iGPTNwGXzo5qYeLRJdP0PUTtCHvMk6E4HmM6wrOM9U6XL9bFoqnnd37Av5HraBObGi6Xe+9Nr0xwaRLrmImX6NiLN/PjRJhDdfXC7Z49agzTMRrxhR0R4mwNezve/6zYt/0JsjeOO9Mm9SScfTEgVYpmnjrGmr7lpFcHul2nbSeZHol+VBs97N2yNVZzBPchKy4wQOIuQ27Ir+iTyP4T5IFC9azY+RtKAVTxW4oAhNbj4n+1L97cx05knRKi5CDBFQnNji/k7QznOak/K9TfFmH1oFho66TR3CCPwkF11C5cuoVaDBXs8MZa/Ht84TNjiJZuQMWehwXUR5a1U0E1dbbpV3KyhUFY/4TGGfeT+NN0YNOf64JZ2AfVnCKrPc8yhH/ff7g8X9TyoHHy+L3WoAKXHvESSF6tzw51sEeHkamsdS2vPlY+IknlpAKH4M5T3OQIMsMWZsKSL8A7GHonAWitbhFalpYvF7VLSWItYBb0wZZT5/yrS8WnaIrGO0ljpSVVXOVey3DxXP3sUPpb6WaRv7E=
